name: CI/CD Next.js -> Minikube

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Checkout the repository code

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Specify the Node.js version

      - name: Install dependencies
        run: npm ci # Install project dependencies

      - name: Build Next.js app
        run: npm run build

      - name: Start Minikube
        uses: medyagh/setup-minikube@master # Or use shell commands
        with:
          minikube-version: "latest"
          kubernetes-version: "latest"
          driver: "docker"

      # 7️⃣ Start Minikube and configure Docker
      - name: Start Minikube
        run: |
          minikube start --driver=docker --kubernetes-version=v1.27.0
          eval $(minikube -p minikube docker-env)

      # 8️⃣ Build Docker image inside Minikube
      - name: Build Docker image
        working-directory: next.js-ci-cd
        run: docker build -t nextjs-app:latest .

      # 9️⃣ Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl rollout status deployment/nextjs-deployment

      # 🔟 Optional: Print service URL
      - name: Get Service URL
        run: minikube service nextjs-service --url
