name: Build and Push Docker Image

on:
  push:
    branches: [main] # Trigger workflow on push to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # Needed for GHCR

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Log in to GitHub Container Registry
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 3️⃣ Build Docker image (Next.js app)
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/nextjs-app:latest .

      # 4️⃣ Push Docker image to GHCR
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/nextjs-app:latest
