name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up Node.js for linting and tests
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: ./webapp

      # 4️⃣ Optional: Run ESLint
      - name: Lint code
        run: npm run lint
        working-directory: ./webapp

      # 5️⃣ Optional: Run tests
      - name: Run tests
        run: npm test
        working-directory: ./webapp
